apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    name: front-end
  name: front-end
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: front-end
    weight: 100
  wildcardPolicy: None

