apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  template:
    spec:
      containers:
      - name: front-end
        image: quay.io/nicolaso/front-end:83440a6
        env:
        - name: RELEASE
          value: "Production release v 83440a6"
        - $patch: replace